import { Inter } from "next/font/google"
import { PropsWithChildren } from "react"
import { ThemeProvider } from "@/components/shared/theme-provider"
import { DirectionProvider } from "@/components/ui/direction"
import { cn } from "@/lib/utils"
import "./globals.css"
import type { Metadata } from "next"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={cn(inter.variable)} dir="ltr" suppressHydrationWarning>
      <body>
        <DirectionProvider dir="ltr">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  )
}
