import { Inter, Noto_Sans_Arabic } from "next/font/google"
import { PropsWithChildren } from "react"
import Header from "@/components/shared/header"
import { ThemeProvider } from "@/components/shared/theme-provider"
import { DirectionProvider } from "@/components/ui/direction"
import "./globals.css"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })
const noto = Noto_Sans_Arabic({ subsets: ["arabic"], variable: "--font-noto" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      className={cn(inter.variable, noto.variable)}
      dir="rtl"
      suppressHydrationWarning
    >
      <body>
        <DirectionProvider direction="rtl">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="fixed size-full bg-background gradient -z-99" />
            <Header />
            {children}
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  )
}
